package com.micky.commonproj.domain.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IP_INFO".
 */
public class IpInfo {

    private Long id;
    private String country;
    private Double country_id;
    private Double area;
    private Double area_id;
    private Double ip;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IpInfo() {
    }

    public IpInfo(Long id) {
        this.id = id;
    }

    public IpInfo(Long id, String country, Double country_id, Double area, Double area_id, Double ip) {
        this.id = id;
        this.country = country;
        this.country_id = country_id;
        this.area = area;
        this.area_id = area_id;
        this.ip = ip;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Double getCountry_id() {
        return country_id;
    }

    public void setCountry_id(Double country_id) {
        this.country_id = country_id;
    }

    public Double getArea() {
        return area;
    }

    public void setArea(Double area) {
        this.area = area;
    }

    public Double getArea_id() {
        return area_id;
    }

    public void setArea_id(Double area_id) {
        this.area_id = area_id;
    }

    public Double getIp() {
        return ip;
    }

    public void setIp(Double ip) {
        this.ip = ip;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
